### PR TITLE
Enums instead of Magic Numbers

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**
Enums instead of Magic Numbers

### CODE REVIEW

**Comment by MajicDesigns** [comment]
Did you intend this to get pushed through to the main repo? Many of the changes are very ESP specific and they are not isolated using #ifdef out so that others don't suffer.

**Comment by diplfranzhoepfinger** [comment]
mainly wanted inform others about a ESP32 Port.

i think not a good idea to push them into master.

**Comment by MajicDesigns** [comment]
OK. I'll close this and leave it for others to find.

Some ideas are good, so I'll port them into the main code next update (none planned at the moment), and I see the class variable precedence initialisation for ESP32 compiler is also in this library...

**Comment by diplfranzhoepfinger** [comment]
class variable precedence initialisation for ESP32 compiler
what do you mean by this ?

**Comment by diplfranzhoepfinger** [comment]
yeah, cool.

**Comment by MajicDesigns** [comment]
"class variable precedence initialisation for ESP32 compiler
what do you mean by this ?"

ESP32 compilers configured for the Arduino IDE, for some reason, produce errors when the variables initialised in a class constructor (after the : and before the opening brace of the constructor) are not initialised in the same order as they are declared in the class. This makes no sense to me - perhaps a warning but it should not be a compile error. I get a lot of 'errors' reported like this one [https://github.com/MajicDesigns/MD_YX5300/issues/8](url)

**Comment by diplfranzhoepfinger** [comment]
yes. had to fix this.

**Pull request closed without merging**
